# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate_app', '0002_auto_20160124_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendareventmodel',
            name='organizer_email',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
