# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocate_app', '0007_auto_20160125_0037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmodel',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='project_id',
        ),
    ]
