# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate_app', '0008_auto_20160125_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='pattern',
            field=models.CharField(default='', max_length=200),
        ),
    ]
