# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_credentialsmodel_flowmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microsoftapicode',
            name='user',
        ),
        migrations.DeleteModel(
            name='MicrosoftAPICode',
        ),
    ]
