# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20160124_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventModel',
        ),
        migrations.DeleteModel(
            name='ProjectModel',
        ),
    ]
